package com.camping.camp.dto;

import java.util.List;
import java.util.Map;

import lombok.Data;

@Data
public class CampDto {
	private List<Object> doList;
	private List<Object> lcList;
	private List<Object> inList;
	private List<Object> sbList;
	private List<Object> siList;
    private String count;
	private String countsix;
	private String encurl;
	private String keyword;
	private String contentid;
	private String facltnm;
	private String lineintro;
	private String intro;
	private String allar;
	private String insrncat;
	private String trsagntno;
	private String bizrno;
	private String facltdivnm;
	private String managedivnm;
	private String mgcdiv;
	private String managesttus;
	private String hvofbgnde;
	private String hvofenddle;
	private String featurenm;
	private String induty;
	private String lctcl;
	private String donm;
	private String sigungunm;
	private String zipcode;
	private String addr1;
	private String addr2;
	private String mapx;
	private String mapy;
	private String direction;
	private String tel;
	private String homepage;
	private String resveurl;
	private String resvecl;
	private String managenmpr;
	private String gnrlsiteco;
	private String autositeco;
	private String glampsiteco;
	private String caravsiteco;
	private String indvdlcaravsiteco;
	private String sitedstnc;
	private String sitemg1width;
	private String sitemg2width;
	private String sitemg3width;
	private String sitemg1vrticl;
	private String sitemg2vrticl;
	private String sitemg3vrticl;
	private String sitemg1co;
	private String sitemg2co;
	private String sitemg3co;
	private String sitebottomcl1;
	private String sitebottomcl2;
	private String sitebottomcl3;
	private String sitebottomcl4;
	private String sitebottomcl5;
	private String tooltip;
	private String glampinnerfclty;
	private String caravinnerfclty;
	private String prmisnde;
	private String operpdcl;
	private String operdecl;
	private String trleracmpnyat;
	private String caravacmpnyat;
	private String toiletco;
	private String swrmco;
	private String wtrplco;
	private String braziercl;
	private String sbrscl;
	private String sbrsetc;
	private String posblfcltycl;
	private String posblfcltyetc;
	private String cltureventat;
	private String clturevent;
	private String exprnprogrmat;
	private String exprnprogrm;
	private String extshrco;
	private String frprvtwrppco;
	private String frprvtsandco;
	private String firesensorco;
	private String themaenvrncl;
	private String eqpmnlendcl;
	private String animalcmgcl;
	private String toureracl;
	private String firstimageurl;
	private String createdtime;
	private String modifiedtime;
}